name: frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  dio: ^5.9.0
  web_socket_channel: ^3.0.3
  flutter_animate: ^4.5.2
  flutter_drawing_board: ^1.0.1+2
  cached_network_image: ^3.4.1
  google_fonts: ^7.1.0
  flutter_svg: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  image: ^4.8.0
  image_gallery_saver_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 图标生成插件
  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 资源配置
  assets:
    - assets/images/
    - assets/images/lens_market/
    - assets/images/home/
    - assets/images/simulation/
    - assets/images/community/
    - assets/images/logo_foreground.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

# -----------------------------------------------------------------
# 👇 下面的配置必须顶格写 (没有任何缩进)，不能在 flutter: 下面
# -----------------------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  
  # 1. 通用/iOS 配置 (使用带背景的完整图)
  image_path: "assets/images/app_icon.png"
  
  # 2. Android 自适应图标专用配置 (核心修改点!)
  # 背景颜色：设置成您的哑光黑
  adaptive_icon_background: "#ffffff" 
  # 前景图片：只放透明底的 Logo
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  
  min_sdk_android: 21
